# Issue Labeler documentation: https://github.com/marketplace/actions/regex-issue-labeler

bug:
  # General:
  #   panic:
  # Terraform CLI:
  #   Provider produced inconsistent final plan
  #   Provider produced inconsistent result after apply
  #   produced an invalid new value
  #   produced an unexpected new value
  # Terraform Plugin SDK:
  #   doesn't support update
  #   Invalid address to set
  - "(panic:|Provider produced inconsistent (final plan|result after apply)|produced an (invalid|unexpected) new value|doesn't support update|Invalid address to set)"

needs-triage:
  - '.*'
