# PR Labeler documentation: https://github.com/marketplace/actions/labeler

dependencies:
  - '.github/dependabot.yml'
  - '**/go.mod'
  - '**/go.sum'

documentation:
  - '**/*.md'
  - 'docs/**/*'
  - 'examples/**/*'

linter:
  - '.github/workflows/*-lint.yml'
  - '.golangci.yml'

provider:
  - '.go-version'
  - 'internal/provider/**/*'
  - 'main.go'

resource:
  - 'internal/provider/resource_*.go'

data-source:
  - 'internal/provider/data_source_*.go'

tests:
  - '**/*_test.go'

tools:
  - 'tools/**/*'
  - 'scripts/**/*'
  - 'GNUMakefile'

workflows:
  - '.github/**/*'
