# GitHub Action reference: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

name: issue-comment-created

on:
  issue_comment:
    types: [created]

permissions:
  issues: write

jobs:
  remove-labels:
    runs-on: ubuntu-latest
    # This job contains steps which are expected to fail.
    continue-on-error: true
    steps:
      - name: Is comment from a collaborator?
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/${{ github.repository }}/collaborators/${{ github.event.sender.login }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Only remove labels if they are NOT a collaborator.
      # Reason being, a collaborator may post a comment and add a waiting-response label.
      - uses: actions-ecosystem/action-remove-labels@v1
        if: ${{ failure() }}
        with:
          labels: |
            stale
            waiting-response
