# GitHub Action reference: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

name: issue-or-pr-closed

on:
  issues:
    types: [closed]
  pull_request_target:
    types: [closed]

permissions:
  issues: write
  pull-requests: write

jobs:
  remove-labels:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        label:
          - 'needs-triage'
          - 'waiting-response'
          - 'needs-rebase'
          - 'merge-conflict'
    steps:
      - name: Remove ${{ matrix.label }} label
        uses: actions-ecosystem/action-remove-labels@v1
        if: contains(github.event.*.labels.*.name, matrix.label)
        with:
          labels: ${{ matrix.label }}
