# GitHub Action reference: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

name: milestone-closed

on:
  milestone:
    types: [closed]

permissions:
  issues: write
  pull-requests: write

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: bflad/action-milestone-comment@v1
        with:
          body: |
            This functionality has been released in [${{ github.event.milestone.title }} of the Terraform GitLab Provider](https://github.com/${{ github.repository }}/blob/${{ github.event.repository.default_branch }}/CHANGELOG.md).  Please see the [Terraform documentation on provider versioning](https://www.terraform.io/language/providers/requirements) or reach out if you need any assistance upgrading.

            For further feature requests or bug reports with this functionality, please create a [new GitHub issue](https://github.com/${{ github.repository }}/issues/new/choose). Thank you!
